# Generated by webapp/tools/sync_from_bot.rb from lib/engine/npc_system.rb. Do not edit; change the bot and re-sync.
# frozen_string_literal: true

module Engine
  module NPCSystem
    COLOUR = 0xe67e22
    TRIGGER_CHANCE = 0.06
    ARC_WEIGHT = 3
    PROGRESS_KEY = 'npc_progress'
    FINISHED_KEY = 'npc_finished'
    LEAVE_KEYS = %w[refuse leave].freeze

    NPC_GEAR = {
      'Charming Amulet' => {
        name: 'Charming Amulet', type: 'accessory', slot: 'accessory',
        description: "Marcus's lucky charm. It never caught him a succubus, but it might help you. +1 Submission, +1 AGI.",
        stat_modifiers: { 'submission' => 1, 'agility' => 1 }, cost: 0, rarity: 2
      }
    }.freeze

    NPCS = {
      'mira' => {
        name: 'Mira', title: 'the Milk-Swollen Delver', tag: 'lactation',
        stages: [
          {
            floors: (8..13),
            intro: 'A curvy woman slumps against the wall, her swollen breasts straining against leather armour that no longer fits. ' \
                   'Milk has soaked dark patches through her shirt, and her nipples press stiffly through the damp fabric. ' \
                   '"Please... take this," she pants, pressing a small pouch into your hand. "I don\'t think I\'ll need it where ' \
                   'I\'m going... my body has other needs now."',
            choices: [
              { key: 'accept', label: 'Accept her gift', text: 'Take the pouch', lp: 20, lust: 8, set: 'gift_given',
                scenes: ['Your fingers brush hers as you take the pouch and she shudders at the contact, her breasts jiggling ' \
                         'with every heavy breath. "They\'re so sensitive now... everything makes them leak," she confesses, blushing.'] },
              { key: 'touch', label: 'Touch her breasts', text: 'Cup her heavy chest', lp: 25, lust: 15, set: 'touched',
                trackers: %w[lactation_events],
                scenes: ['You cup one of her breasts. It overflows your hand, warm and impossibly heavy.',
                         '"Aahn!" Milk sprays through her shirt and soaks your palm. "They\'re so sensitive... please..."'] },
              { key: 'refuse', label: 'Refuse', text: 'Turn her gift down', set: 'refused',
                scenes: ['You push the pouch back into her hands. She sighs, disappointed, and her breasts heave with the motion.'] }
            ]
          },
          {
            floors: (15..20), after: %w[touched gift_given],
            intro: 'You find Mira again, topless now. Her breasts have grown enormous, heaving with every breath, and milk drips ' \
                   'constantly from her dark, puffy nipples. "I can\'t stop... they\'re so full and aching," she begs, cupping ' \
                   'them in both hands. "I need someone to milk me or I\'ll burst..."',
            choices: [
              { key: 'milk', label: 'Milk her', text: 'Relieve the pressure', lp: 30, lust: 20, set: 'milked',
                trackers: %w[lactation_events],
                scenes: ['You kneel in front of Mira and squeeze. Warm cream sprays out in thick streams as she moans in relief.',
                         '"Yesss... don\'t stop..." She arches her back, pushing her tits into your hands. The sweet smell of her ' \
                         'milk fills the air and your own body answers with a needy ache.'] },
              { key: 'suckle', label: 'Suckle', text: 'Drink straight from her', lp: 40, lust: 25, heal: 15, set: 'suckled',
                trackers: %w[lactation_events],
                scenes: ['You take one dark nipple into your mouth. Sweet cream floods your tongue and she cries out, holding your ' \
                         'head to her breast. "Drink deeply... fill yourself with me..."',
                         'The milk spreads warmth through your belly — it steadies your will even as it stokes your desire.'] },
              { key: 'refuse', label: 'Refuse', text: 'Leave her aching', set: 'refused',
                scenes: ['You shake your head. She stares after you with desperate, pleading eyes. "Please... it hurts..."'] }
            ]
          },
          {
            floors: (22..27), after: %w[milked suckled],
            intro: 'Mira finds you this time. Her breasts hang heavy to her navel, nipples dripping a steady stream. ' \
                   '"I need you again," she pants. "And my milk is special now — drink it, and it\'ll help you resist this ' \
                   'tower\'s corruption..." She lifts one breast towards you, offering.',
            choices: [
              { key: 'milk_drink', label: 'Milk and drink', text: 'Take everything she offers', lp: 50, lust: 25, heal: 30,
                set: 'blessed', trackers: %w[lactation_events],
                condition: { key: 'miras_blessing', name: "Mira's Blessing", floors: 3,
                             effects: { 'resistance' => 2, 'lust_mult' => 0.85 } },
                scenes: ['You milk her heavy breasts until she is gasping, then drink straight from her fountaining nipples. ' \
                         'The cream is thick and sweet.',
                         '"Yes... drink it all... let me fill you..." Your lust climbs with every swallow, but your mind clears ' \
                         'and hardens against the tower\'s pull.'] },
              { key: 'milk_only', label: 'Just milk her', text: "Help, but don't drink", lp: 35, lust: 20, set: 'milked_only',
                trackers: %w[lactation_events],
                scenes: ['You milk Mira until the pressure eases, but turn away when she offers you a taste. She sighs with ' \
                         'relief, though her eyes are disappointed.'] },
              { key: 'refuse', label: 'Refuse', text: 'Turn her away again', set: 'fought',
                fight: { type: :beast, name: 'Desperate HuCow Mira',
                         text: 'Her eyes harden. "Fine! If you won\'t help me, you can be my next milk cow!" She lunges, ' \
                               'tearing at your clothes and trying to force her leaking nipple to your lips!' } }
            ]
          }
        ]
      },

      'lillia' => {
        name: 'Lillia', title: 'the Reshaped Adventurer', tag: 'bimbofication',
        stages: [
          {
            floors: (3..7),
            intro: 'A platinum-haired adventurer is fighting a pulsating piece of living armour that is trying to merge with her. ' \
                   'Her breasts are already half exposed as the armour moulds them into perfect, gravity-defying spheres. ' \
                   '"I can\'t get this thing off! It\'s... changing me... making me *hotter*..." Her voice comes out breathier ' \
                   'than it should.',
            choices: [
              { key: 'help', label: 'Help her', text: 'Peel the armour off', lust: 6, set: 'helped', trackers: %w[bimbo_transformations],
                condition: { key: 'giggly_glow', name: 'Giggly Glow', floors: 2,
                             effects: { 'satisfy_bonus' => 0.1, 'resistance' => -1 } },
                scenes: ['You peel the living armour away and her reshaped breasts bounce free. "Thank you!" she giggles, ' \
                         'oddly vacant. "Here — it makes you feel *really* good!"',
                         'She presses a pink vial into your hand. You drink it, and a warm, fizzy glow settles over your thoughts.'] },
              { key: 'touch', label: 'Touch her breasts', text: 'Feel the change', lp: 25, lust: 18, set: 'touched',
                trackers: %w[bimbo_transformations],
                scenes: ['You reach out and cup her transforming breasts. They are soft yet firm, perfectly round and warm.',
                         '"Ooooh..." she moans as the armour finishes its work. "They feel *so* much better now..."'] },
              { key: 'push', label: 'Push her in', text: 'Let the armour finish her', set: 'doll',
                fight: { type: :mimic, name: 'Living Doll Lillia',
                         text: 'You shove her into the armour. It wraps around her curves and her expression goes blank and ' \
                               'blissful. "Must... please..." she giggles, reaching for you with doll-smooth hands.' } }
            ]
          },
          {
            floors: (10..14), after: %w[touched],
            intro: 'Lillia bounces up to you in barely-there armour that does nothing but frame her exaggerated hourglass ' \
                   'figure. "Like, I totally don\'t need *real* armour anymore," she giggles. "This shows off my titties way ' \
                   'better! Wanna touch?" She arches her back, presenting herself.',
            choices: [
              { key: 'touch', label: 'Touch her breasts', text: 'Take her up on it', lp: 30, lust: 25, set: 'touched_again',
                trackers: %w[bimbo_transformations],
                scenes: ['Her breasts are unnaturally firm yet soft, warming under your palms. "Ooooh, yeah..." she moans, ' \
                         'pushing them into your hands. "They\'re so much more fun now..."'] },
              { key: 'fuck', label: 'Fuck her', text: 'Bend her over', lp: 50, lust: 30, set: 'fucked', caged: true,
                trackers: %w[bimbo_transformations],
                by_part: {
                  'penis' => ['You bend Lillia over and sink your cock into her dripping pussy. She squeals as you thrust deep. ' \
                              '"Yes! Fuck me! Make me your dumb little fucktoy!"']
                },
                otherwise: ['You bend Lillia over and bury your fingers in her dripping pussy, curling them until she squeals. ' \
                            '"Yes! Like that! Make me your dumb little fucktoy!"'] }
            ]
          }
        ]
      },

      'elara' => {
        name: 'Sister Elara', title: 'the Latex Priestess', tag: 'latex',
        stages: [
          {
            floors: (10..15),
            intro: 'A woman in holy vestments kneels in a ring of pulsing latex tendrils. They coil up her legs, rising higher ' \
                   'as she struggles weakly. "No... must resist... this sinful material..." Her prayers melt into moans as the ' \
                   'latex creeps up her thighs, and her nipples stiffen through her robes where it touches them.',
            choices: [
              { key: 'help', label: 'Pull it off', text: 'Try to free her', lust: 12, set: 'helped', trackers: %w[latex_events],
                condition: { key: 'latex_touched', name: 'Latex-Slick', floors: 2,
                             effects: { 'agility' => -1, 'satisfy_bonus' => 0.05 } },
                scenes: ['You grab the latex and pull, but it is far too strong — and some of it clings to your hands, ' \
                         'warm and slick.',
                         'The priestess moans as it flows over her breasts. "It... it feels... good..."'] },
              { key: 'watch', label: 'Watch', text: 'Watch her transform', lust: 20, set: 'watched', trackers: %w[latex_events],
                scenes: ['You watch the latex swallow her whole, smoothing her into a gleaming, perfect doll.',
                         'Her last moan turns into a giggle. "So... shiny... so... good..."'] },
              { key: 'encourage', label: 'Encourage her', text: 'Whisper her into it', lp: 40, lust: 25, set: 'encouraged',
                trackers: %w[latex_events],
                scenes: ['"Yes... let it change you," you whisper. "Become one with it..."',
                         'She looks at you with gratitude as the latex seals over her. "Thank you... for showing me the way..."'] }
            ]
          },
          {
            floors: (18..23), after: %w[watched encouraged],
            intro: 'The former priestess glides towards you, a living latex doll. Her body is smooth and gleaming — ' \
                   'featureless except for her voluptuous curves and the slick, glistening folds between her thighs. ' \
                   '"Join me... become like me..." she whispers, monotone yet enticing, beckoning with shiny hands.',
            choices: [
              { key: 'join', label: 'Let her change you', text: 'Become latex', lp: 60, lust: 35, set: 'completed',
                special: :latexdoll, trackers: %w[latex_events],
                scenes: ['You let her touch you, and the latex spreads from her fingers over your skin, cool and then warm, ' \
                         'squeezing every curve.',
                         '"Yes... become like me... no more worries... no more thoughts... only pleasure..."'] },
              { key: 'fuck', label: 'Fuck her', text: 'Use her latex body', lp: 50, lust: 30, set: 'fucked', caged: true,
                trackers: %w[latex_events],
                by_part: {
                  'penis' => ['You thrust into her latex pussy. It is surprisingly warm and tight, gripping you perfectly. ' \
                              '"Yes... fill me... make me *feel* something..." she moans in her flat voice.']
                },
                otherwise: ['You press her against the wall and grind against her slick latex body, your fingers sliding into ' \
                            'her gleaming folds. "Yes... make me *feel* something..." she moans in her flat voice.'] }
            ]
          }
        ]
      },

      'marcus' => {
        name: 'Marcus', title: 'the Succubus Chaser',
        stages: [
          {
            floors: (9..12),
            intro: 'A man draped in cheap charms and love potions kicks a wall in frustration. "Another day wasted! No ' \
                   'succubus will have me!" He notices you. "Maybe you can help? I\'ve tried *everything* and they just ' \
                   'won\'t notice me." The bulge in his trousers makes his frustration obvious.',
            choices: [
              { key: 'help', label: 'Give him LP', text: 'Fund his quest', cost: 10, heal: 10, set: 'helped',
                scenes: ['"Thank you! Maybe *now* one will notice me!" He scurries off, beaming. Helping him leaves you ' \
                         'feeling oddly lighter.'] },
              { key: 'join', label: 'Let him tag along', text: 'Travel together for a while', set: 'joined', special: :amulet,
                scenes: ['Marcus follows you for a few rooms, surprisingly useful in a scrap — until a succubus finally ' \
                         'steps out of the shadows. She dismisses him with a glance... then crooks a finger, and he goes ' \
                         'running. He tosses you his lucky charm on the way.'] },
              { key: 'charm', label: 'Charm him', text: 'Show him what a real demon feels like', needs_form: %w[succubus incubus],
                lp: 30, lust: 15, set: 'devoted',
                condition: { key: 'marcus_devotion', name: "Marcus's Devotion", floors: 5,
                             effects: { 'trap_avoid_bonus' => 0.25 } },
                scenes: ['You let your demonic charm wash over him. His eyes go wide. "You... you\'re one of them!"',
                         '"Let me be yours! I\'ll do anything — I\'ll even walk into the traps first!" He falls to his knees ' \
                         'and kisses your feet.'] }
            ]
          }
        ]
      },

      'thomas' => {
        name: 'Thomas', title: 'the Over-Geared Delver',
        stages: [
          {
            floors: (16..20),
            intro: 'A man staggers towards you, smothered in living mimic gear. His breastplate keeps trying to swallow his ' \
                   'chest, his leggings squeeze his thighs, and his gloves keep dragging his hands down to stroke himself. ' \
                   '"Please, help me! I spent all my LP levelling up and now I can\'t afford to take this stuff off!" His ' \
                   'cock strains, hard and leaking, against the living leggings.',
            choices: [
              { key: 'give', label: 'Give him LP', text: 'Pay for his release', cost: 15, lust: 12, set: 'helped',
                condition: { key: 'living_breastplate', name: 'Clinging Breastplate', floors: 3,
                             effects: { 'resistance' => 1, 'lust_mult' => 1.1 } },
                scenes: ['The moment the LP changes hands, his breastplate peels away — and leaps straight onto *you*.',
                         '"Oh no — it likes you now!" he gasps, as it clamps around your chest and starts kneading.'] },
              { key: 'fight', label: 'Fight him', text: 'Take his LP by force', lp: 25, lust: 18, set: 'robbed',
                scenes: ['You land a single hit and every piece of his gear activates at once. "Can\'t... take it!" he wails ' \
                         'as it works him over relentlessly until he collapses, twitching.',
                         'You gather the LP that spills from his pockets and leave him to his outfit.'] }
            ]
          }
        ]
      },

      'alex' => {
        name: 'Alex', title: 'the Lost Newbie',
        stages: [
          {
            floors: (21..24),
            intro: 'A nervous delver in starter gear flinches as you approach. "This place is... intense," Alex stammers, ' \
                   'blushing. "I keep getting caught in these... *interesting* traps..." Their clothes are dishevelled and ' \
                   'they smell unmistakably of arousal.',
            choices: [
              { key: 'help', label: 'Help them', text: 'Free them from the trap', lp: 20, set: 'helped',
                scenes: ['You pry the trap open. "Thank you!" Alex presses some LP into your hands. "I don\'t think I\'m ' \
                         'making it out of here anyway..."'] },
              { key: 'teach', label: 'Teach them', text: 'Share survival tips', lust: 10, heal: 10, set: 'taught',
                scenes: ['You walk Alex through spotting traps and picking fights. "I... appreciate it," they say, blushing. ' \
                         '"But I think I might be starting to *like* it here..."'] }
            ]
          },
          {
            floors: (26..29), after: %w[helped],
            intro: 'Alex is caught again — but this time they look far less panicked. "Oh... hello again," they moan, hips ' \
                   'rocking helplessly as the trap works them over. "This one feels... really good, actually..."',
            choices: [
              { key: 'help', label: 'Help again', text: 'Pull them free', lp: 15, set: 'helped_again',
                scenes: ['You free Alex, though they seem reluctant to leave. "Are you sure I... have to?" they ask, even as ' \
                         'you pull them out.'] },
              { key: 'watch', label: 'Watch', text: 'Let them enjoy it', lp: 25, lust: 20, set: 'watched',
                scenes: ['You watch Alex come apart in the trap, face twisting in bliss. "Oh yesss..." they cry as it ' \
                         'finally releases them. "That was... amazing..."'] }
            ]
          },
          {
            floors: (30..35), after: %w[helped_again],
            intro: 'You find Alex one last time, lying willingly in a nest of tentacles that stroke and fill them. ' \
                   '"I\'ve decided to stay," they smile dreamily. "This tower brings such pleasure... Would you like to join ' \
                   'me? Just for a little while?"',
            choices: [
              { key: 'join', label: 'Join them', text: 'Step into the tentacles', lp: 60, lust: 40, set: 'joined',
                scenes: ['You step in beside Alex and the tentacles wrap around you both, stroking, squeezing and filling, ' \
                         'until the two of you are a tangle of moans and shaking limbs.'] },
              { key: 'leave', label: 'Leave them', text: 'Let them have their bliss', lust: 15, set: 'left',
                scenes: ['"Thank you for showing me the way," Alex calls after you. You walk on, still flushed from the sight.'] }
            ]
          }
        ]
      },

      'milking_station' => {
        name: 'Milking Station', title: nil, tag: 'lactation', repeatable: true,
        stages: [
          {
            floors: (15..25),
            intro: 'A long room hums with machinery. Women are strapped into milking frames, their breasts — large to ' \
                   'enormous — sealed into rhythmic pumps. Some moan in pleasure, others whimper. A technician in a lab ' \
                   'coat smiles at you. "Care to try our special milk? Red is an aphrodisiac, blue restores willpower, ' \
                   'green heightens sensitivity..."',
            choices: [
              { key: 'red', label: 'Red milk', text: 'Aphrodisiac', lp: 15, lust: 30,
                condition: { key: 'red_milk', name: 'Red Milk Heat', floors: 3,
                             effects: { 'lust_mult' => 1.2, 'submit_lp_bonus' => 3 } },
                scenes: ['The red milk is warm and thick with a cinnamon bite. Heat floods your body until every brush of ' \
                         'fabric makes you gasp.'] },
              { key: 'blue', label: 'Blue milk', text: 'Restores willpower', heal: 20,
                condition: { key: 'blue_milk', name: 'Blue Milk Clarity', floors: 3,
                             effects: { 'lust_mult' => 0.85, 'resistance' => 1 } },
                scenes: ['The blue milk is cool and minty. Your head clears as the tower\'s haze recedes.'] },
              { key: 'green', label: 'Green milk', text: 'Heightens sensitivity', lp: 18, lust: 20,
                condition: { key: 'green_milk', name: 'Green Milk Sensitivity', floors: 3,
                             effects: { 'lust_mult' => 1.15, 'satisfy_bonus' => 0.1 } },
                scenes: ['The green milk tingles on your tongue and spreads under your skin. Even the air feels like a caress.'] },
              { key: 'become', label: 'Be milked', text: 'Take a free frame', needs_part: 'breasts', lp: 20, lust: 25,
                trackers: %w[being_milked_events lactation_events],
                condition: { key: 'milked_dry', name: 'Milked Dry', floors: 2,
                             effects: { 'submission' => 1, 'submit_lp_bonus' => 2 } },
                scenes: ['The technician straps you into an empty frame and seals the cups over your breasts. The pumps ' \
                         'start to pull — an ache that melts into helpless, rhythmic pleasure as you are milked dry.'] }
            ]
          }
        ]
      },

      'trapped_delver' => {
        name: 'Trapped Delver', title: nil, repeatable: true,
        stages: [
          {
            name: 'Delver in the Stocks', floors: (4..25), tag: 'bondage',
            intro: 'A woman is locked in a set of stocks, head and wrists pinned, her bare ass raised and helpless. ' \
                   '"Please... let me out and I\'ll make it worth your while," she begs — though her glistening pussy ' \
                   'suggests she isn\'t *only* suffering.',
            choices: [
              { key: 'help', label: 'Release her', text: 'Unlock the stocks', lp: 15, lust: 20,
                scenes: ['You unlock the stocks and she throws her arms around you. "Thank you! Let me reward you properly..."'],
                by_part: { 'penis' => ['She sinks to her knees and takes your cock deep into her mouth, humming happily.'],
                           'vagina' => ['She sinks to her knees and buries her tongue between your thighs until your legs shake.'] },
                otherwise: ['She sinks to her knees and worships you with her lips and tongue until your legs shake.'],
                caged: true },
              { key: 'use', label: 'Use her', text: 'Take what she is offering', lp: 20, lust: 30, caged: true,
                by_part: { 'penis' => ['You step behind her and thrust into her exposed pussy. "Yes... take me... fill me..." ' \
                                       'she begs, pushing back against every stroke.'] },
                otherwise: ['You step behind her and slide your fingers into her dripping pussy, then your tongue, until she ' \
                            'is begging and pushing back against your face.'] }
            ]
          },
          {
            name: 'Glory Hole Wall', floors: (4..25),
            intro: 'Muffled moans come from behind a wall riddled with holes. Someone is trapped on the other side, their ' \
                   'body offered through the openings while unseen hands and creatures take turns with them.',
            choices: [
              { key: 'help', label: 'Free them', text: 'Find the release lever', lp: 10, lust: 15, caged: true,
                scenes: ['You find a lever and the wall swings open. A young man stumbles out, sticky and breathless. "Thank you..."'],
                by_part: { 'penis' => ['He thanks you with a quick, eager blowjob before hurrying off.'],
                           'vagina' => ['He thanks you with his tongue, quick and eager, before hurrying off.'] },
                otherwise: ['He thanks you with a deep, breathless kiss before hurrying off.'] },
              { key: 'use', label: 'Use the holes', text: 'Join the queue', lp: 20, lust: 35, caged: true,
                by_part: { 'penis' => ['You pick a hole and push your cock through. Whoever is trapped there moans around ' \
                                       'you, and you use them until you are shaking and breathless.'],
                           'vagina' => ['You press your pussy to a hole and a hungry tongue answers at once, lapping at you ' \
                                        'until you are shaking and breathless.'] },
                otherwise: ['You explore the offered body with your hands, teasing and stroking until the moans behind the ' \
                            'wall turn desperate.'] }
            ]
          },
          {
            name: 'Mirror Gazer', floors: (4..25), tag: 'voyeurism',
            intro: 'A woman stares blankly into a shifting mirror, one hand buried in her panties, rubbing furiously. ' \
                   '"It shows me such beautiful things... makes me so wet..." Her juices drip down her thighs.',
            choices: [
              { key: 'help', label: 'Break the mirror', text: 'Snap her out of it', lp: 15, lust: 20, caged: true,
                scenes: ['You shatter the mirror. She blinks. "What... where am I?" Then she notices the state she is in and ' \
                         'blushes crimson. "Let me... repay you."'],
                by_part: { 'penis' => ['She drops to her knees and takes your cock in her mouth, sucking with grateful enthusiasm.'],
                           'vagina' => ['She drops to her knees and laps at your pussy with grateful enthusiasm.'] },
                otherwise: ['She drops to her knees and kisses her way up your thighs with grateful enthusiasm.'] },
              { key: 'join', label: 'Join her', text: 'Touch yourself beside her', lp: 15, lust: 40,
                scenes: ['You sit beside her and start touching yourself. She notices and beckons. "Come... let\'s do it ' \
                         'together..." You watch each other, hands moving faster and faster, until you are both panting.'] }
            ]
          },
          {
            name: 'Mimic Chest Victim', floors: (4..25),
            intro: 'A woman is stuck waist-deep in a treasure chest, the lid clamped over her hips, her legs spread wide and ' \
                   'her pussy glistening. "Help! It won\'t let me go!" she cries — though her voice betrays more arousal ' \
                   'than fear.',
            choices: [
              { key: 'help', label: 'Free her', text: 'Pry the lid open', lp: 12, lust: 20,
                scenes: ['You strain at the lid but it won\'t budge, and every tug makes the chest shift against her. ' \
                         '"Keep trying... oh yes... right there..."',
                         'When she finally comes, the chest spits her out. "Thank you... oh, thank you..."'] },
              { key: 'use', label: 'Use her', text: 'Take advantage', lp: 20, lust: 35, caged: true,
                by_part: { 'penis' => ['You thrust into her exposed pussy. "Yes! Use me! Fill me!" she cries as the chest ' \
                                       'holds her still for every stroke.'] },
                otherwise: ['You kneel between her legs and work her with your fingers and tongue. "Yes! Don\'t stop!" she ' \
                            'cries as the chest holds her still.'] }
            ]
          }
        ]
      }
    }.freeze

    module_function

    def npc(id)
      NPCS[id.to_s]
    end

    def progress(player)
      Hash(player.tracker_hash[PROGRESS_KEY])
    end

    def set_progress!(player, id, value)
      player.set_tracker!(PROGRESS_KEY, progress(player).merge(id.to_s => value))
    end

    def finished?(id, state)
      spec = npc(id)
      return true unless spec
      return false if state.nil? || spec[:repeatable]

      spec[:stages].none? { |stage| Array(stage[:after]).include?(state) }
    end

    def finished_counts(player)
      Hash(player.tracker_hash[FINISHED_KEY])
    end

    def record_finished!(player, id, log)
      counts = finished_counts(player)
      player.set_tracker!(FINISHED_KEY, counts.merge(id => counts[id].to_i + 1))
      player.bump_tracker!('npc_stories_finished')
      log << "_#{npc(id)[:name]}'s story is over for this run — you may cross paths again in a future run._"
    end

    def reset_finished!(player)
      state = progress(player)
      kept = state.reject { |id, value| finished?(id, value) }
      player.set_tracker!(PROGRESS_KEY, kept) unless kept.size == state.size
    end

    def tag_ok?(player, tag)
      tag.nil? || Engine::ContentOptions.enabled?(player, tag)
    end

    def stage_available?(player, id, spec, stage)
      return false unless stage[:floors].include?(player.current_floor.to_i)
      return false unless tag_ok?(player, stage[:tag] || spec[:tag])
      return true if spec[:repeatable]

      state = progress(player)[id]
      stage[:after] ? Array(stage[:after]).include?(state) : state.nil?
    end

    def next_stage_index(player, id)
      spec = npc(id) or return nil
      state = progress(player)[id]
      return 0 if state.nil? || spec[:repeatable]

      spec[:stages].index { |stage| Array(stage[:after]).include?(state) }
    end

    def available(player)
      NPCS.flat_map do |id, spec|
        spec[:stages].each_with_index.select { |stage, _| stage_available?(player, id, spec, stage) }
                     .map { |_, i| [id, i] }
      end
    end

    def should_trigger?(player)
      return false if player.active_event? || player.in_combat || player.encounter_data

      rand < TRIGGER_CHANCE
    end

    def maybe_start!(player)
      return nil unless should_trigger?(player)

      options = available(player)
      return nil if options.empty?

      weights = options.map { |id, _| npc(id)[:repeatable] ? 1 : ARC_WEIGHT }
      roll = rand * weights.sum
      pick = options.zip(weights).find { |_, w| (roll -= w) <= 0 }&.first || options.last
      start!(player, *pick)
    end

    def start!(player, id, stage_index)
      spec = npc(id)
      stage = spec[:stages][stage_index]
      name = display_name(spec, stage)
      level = player.current_floor
      player.store_event!(type: 'npc', npc: id, stage: stage_index, level: level, mode: 'choice', name: name)
      {
        ok: true,
        mode: :choice,
        name: name,
        colour: COLOUR,
        log: ["**Floor #{level}** — someone else is down here.", { scene: stage[:intro] },
              *Array(Engine::ChastitySystem.reminder(player)).map { |r| "_#{r}_" }, 'What do you do?'],
        choices: choices(player, id, stage_index)
      }
    end

    def display_name(spec, stage)
      stage[:name] || [spec[:name], spec[:title]].compact.join(', ')
    end

    def stage_for(id, stage_index)
      npc(id)&.dig(:stages, stage_index.to_i)
    end

    def option_allowed?(player, opt)
      return false if opt[:needs_part] && !player.body_parts_list.map(&:to_s).include?(opt[:needs_part])
      return false if opt[:needs_form] && !Array(opt[:needs_form]).include?(player.active_transformation_key.to_s)

      true
    end

    def stage_choices(player, stage)
      list = stage[:choices].select { |c| option_allowed?(player, c) }
      unless list.any? { |c| LEAVE_KEYS.include?(c[:key]) }
        list += [{ key: 'leave', label: 'Walk away', text: 'Leave them be', scenes: ['You leave them to it and move on.'] }]
      end
      list
    end

    def choices(player, id, stage_index)
      stage = stage_for(id, stage_index) or return []
      stage_choices(player, stage).map do |c|
        cost = c[:cost].to_i
        style = LEAVE_KEYS.include?(c[:key]) ? :secondary : (c[:fight] ? :danger : :primary)
        if cost.positive?
          { key: c[:key], label: "#{c[:label]} (#{cost} LP)", text: c[:text], style: style, disabled: player.lp < cost }
        else
          { key: c[:key], label: c[:label], text: c[:text], style: style }
        end
      end
    end

    def resolve!(player, data, key, log)
      id = data[:npc].to_s
      spec = npc(id)
      stage = stage_for(id, data[:stage])
      return { ok: false } unless spec && stage

      opt = stage_choices(player, stage).find { |c| c[:key] == key.to_s }
      return { ok: false } unless opt

      cost = opt[:cost].to_i
      if cost.positive?
        return { ok: false, message: "You need **#{cost} LP** for that (you have #{player.lp})." } unless player.spend_lp!(cost)

        log << "You hand over **#{cost} LP** (now #{player.lp})."
      end

      log.concat(scenes_for(player, spec, opt))
      if opt[:set] && !spec[:repeatable]
        set_progress!(player, id, opt[:set])
        record_finished!(player, id, log) if finished?(id, opt[:set])
      end

      if opt[:fight]
        log << { scene: opt[:fight][:text] }
        return { ok: true, fight: opt[:fight] }
      end

      apply_rewards!(player, opt, log)
      player.bump_tracker!('npc_encounters') unless opt[:key] == 'leave'
      { ok: true }
    end

    def scenes_for(player, spec, opt)
      parts = Engine::ChastitySystem.scene_parts(player)
      out = Array(opt[:scenes]).map { |s| { scene: s } }
      if opt[:by_part] || opt[:otherwise]
        part = Hash(opt[:by_part]).keys.find { |p| parts.include?(p) }
        pool = part ? opt[:by_part][part] : opt[:otherwise]
        out << { scene: Array(pool).sample } if Array(pool).any?
      end
      out.concat(Engine::ChastitySystem.scenes(player, :partner, actor: spec[:name])) if opt[:caged]
      out
    end

    def apply_rewards!(player, opt, log)
      lp = opt[:lp].to_i
      lust = opt[:lust].to_i
      heal = opt[:heal].to_i
      bits = []
      if lp.positive?
        player.gain_lp!(lp)
        bits << "**+#{lp} LP**"
      end
      if heal.positive?
        player.heal_defiance!(heal)
        bits << "defiance **+#{heal}** (now #{player.defiance}/#{player.max_defiance})"
      end
      if lust.positive?
        player.gain_lust!(lust)
        bits << "lust **+#{lust}** (now #{player.lust})"
      end
      log << bits.join(' · ') if bits.any?

      Engine::FetishEvents.apply_condition!(player, opt[:condition], log) if opt[:condition]
      Array(opt[:trackers]).each { |t| player.bump_tracker!(t) }
      apply_special!(player, opt[:special], log) if opt[:special]
    end

    def apply_special!(player, special, log)
      case special
      when :latexdoll then unlock_form!(player, 'latexdoll', log)
      when :amulet then grant_gear!(player, 'Charming Amulet', log)
      end
    end

    def unlock_form!(player, key, log)
      form = Engine::TransformationSystem.get(key)
      if player.unlocked_transformations.include?(key)
        log << "_The latex recognises one of its own and settles back into your skin — you're already a **#{form[:name]}**._"
        return
      end
      player.update(transformations: player.unlocked_transformations + [key])
      log << "**New hybrid form unlocked:** #{form[:name]} — _#{form[:description]}_ (take it with `/transformation`)"
    end

    def grant_gear!(player, name, log)
      tpl = NPC_GEAR.fetch(name)
      item = ::Equipment.find_or_create(name: name) { |e| Engine::Treasure.apply_template!(e, tpl) }
      Engine::Treasure.apply_template!(item, tpl)
      item.save_changes
      if player.owns_equipment?(item.id)
        player.gain_lp!(15)
        log << "_You already have a **#{name}**, so you pawn this one off for **+15 LP**._"
        return
      end
      result = player.grant_equipment!(item)
      log << "You receive the **#{name}** — _#{tpl[:description]}_ #{result[:message]}"
    end

    def monster_for(player, fight, level)
      monster = Engine::MonsterTypes.generate_monster(level, player: player, type: fight[:type], elite: false)
      monster.merge(name: fight[:name] || monster[:name])
    end
  end
end
