# Generated by webapp/tools/sync_from_bot.rb from lib/engine/transformation_system.rb. Do not edit; change the bot and re-sync.
# frozen_string_literal: true

module Engine
  module TransformationSystem
    PETKIN = {
      requirement: { petplay_events: 5, beast_submissions: 10 }
    }.freeze

    TRANSFORMATIONS = {
      'kitten' => PETKIN.merge(
        name: 'Kitten', group: 'Beast',
        description: "You've developed feline features — soft ears, a swishing tail, and heightened senses",
        appearance: ['cat ears', 'flexible spine', 'retractable claws', 'cat tail'],
        buff: 'Feline Agility', buff_description: '+20% dodge chance, +10% seduction chance',
        effects: { 'dodge_bonus' => 0.2, 'satisfy_bonus' => 0.1 }
      ),
      'puppy' => PETKIN.merge(
        name: 'Puppy', group: 'Beast',
        description: "You've developed canine features — floppy ears, a wagging tail, and an eager-to-please heart",
        appearance: ['floppy ears', 'wagging tail', 'keen nose', 'padded palms'],
        buff: 'Canine Loyalty', buff_description: '+25% damage resistance, +15% LP gain from submission',
        effects: { 'damage_reduction' => 0.75, 'submit_lp_mult' => 1.15 }
      ),
      'hucow' => {
        name: 'HuCow', group: 'Beast',
        description: "You've developed bovine features — heavy, leaking breasts and a docile, milkable body",
        requirement: { being_milked_events: 3, lactation_events: 3, weight_gain_events: 3 },
        appearance: ['multiple breasts', 'udder', 'small horns', 'cow tail'],
        events: { 'lactation' => 35, 'weight_gain' => 25 },
        buff: 'Bovine Endurance', buff_description: '+30% damage resistance, +20% LP from being milked',
        effects: { 'damage_reduction' => 0.7, 'lactation_event_lp_mult' => 1.2 }
      },
      'harpy' => {
        name: 'Harpy', group: 'Beast',
        description: "You've developed avian features including wings and clawed feet",
        requirement: { petplay_events: 5, body_growth_events: 3, exhibitionism_events: 3 },
        appearance: ['feathered arms/wings', 'clawed feet', 'lighter bones'],
        buff: 'Avian Grace', buff_description: '+25% dodge chance, +15% flee chance',
        effects: { 'dodge_bonus' => 0.25, 'flee_bonus' => 0.15 },
        special_event: 'Wing Display',
        special_event_description: 'Sometimes your wings unfurl dramatically, and the monster forgets to attack',
        special: { kind: :stun, chance: 0.12,
                   text: 'Your wings unfurl in a dramatic display — the %<name>s stares, transfixed, and forgets to attack!' }
      },
      'slimekin' => {
        name: 'Slimekin', group: 'Beast',
        description: 'Your body has become partially gelatinous and amorphous',
        requirement: { slime_submissions: 10, inflation_events: 3 },
        appearance: ['semi-translucent skin', 'amorphous limbs', 'no fixed shape'],
        buff: 'Amorphous Form', buff_description: '+20% damage resistance, can squeeze through small openings',
        effects: { 'damage_reduction' => 0.8 },
        special_event: 'Absorption',
        special_event_description: "When struck, you sometimes partially absorb the attacker and regain defiance",
        special: { kind: :absorb, chance: 0.2,
                   text: 'Your gelatinous body swallows part of the %<name>s as it grabs you — you absorb **%<amount>s** defiance!' }
      },
      'succubus' => {
        name: 'Succubus', group: 'Demon',
        description: "You've transformed into a creature of seduction and dreams",
        requirement: { demon_submissions: 15, futanari_events: 3 },
        appearance: ['small wings', 'small horns', 'supernatural beauty', 'tail'],
        buff: 'Seductive Power', buff_description: '+30% seduction chance, +10 LP from sexual acts',
        effects: { 'satisfy_bonus' => 0.3, 'submit_lp_bonus' => 10 },
        special_event: 'Dream Walking',
        special_event_description: "Sometimes you slip into the monster's dreams, gaining LP without being touched",
        special: { kind: :dream, chance: 0.15,
                   text: "You slip into the %<name>s's waking dreams and feed on its fantasies — **+%<amount>s LP**." }
      },
      'incubus' => {
        name: 'Incubus', group: 'Demon',
        description: "You've transformed into a creature of seduction and desire",
        requirement: { demon_submissions: 15, futanari_events: 3 },
        appearance: ['supernatural charm', 'small wings', 'small horns'],
        buff: 'Incubus Charm', buff_description: '+30% seduction chance, +10 LP from sexual acts',
        effects: { 'satisfy_bonus' => 0.3, 'submit_lp_bonus' => 10 },
        special_event: 'Shadow Form',
        special_event_description: 'Sometimes you melt into shadow and the monster loses you entirely',
        special: { kind: :stun, chance: 0.12,
                   text: 'You melt into shadow — the %<name>s lunges at nothing and loses its turn!' }
      },
      'imp' => {
        name: 'Imp', group: 'Demon',
        description: "You've transformed into a small, mischievous lesser demon",
        requirement: { demon_submissions: 10, body_reduction_events: 3, mind_control_events: 3 },
        appearance: ['small stature', 'wings', 'horns', 'tail'],
        buff: 'Impish Agility', buff_description: '+20% dodge chance, +15% surprise attack chance (double damage)',
        effects: { 'dodge_bonus' => 0.2, 'crit_chance' => 0.15 },
        special_event: 'Prank',
        special_event_description: 'Sometimes you play a prank on the monster, stunning it',
        special: { kind: :stun, chance: 0.12,
                   text: 'You pull a wicked prank on the %<name>s — it reels, stunned, and loses its turn!' }
      },
      'dryad' => {
        name: 'Dryad', group: 'Plant',
        description: "You've become one with the plant life of the tower",
        requirement: { plant_submissions: 10, objectification_events: 3 },
        appearance: ['bark skin', 'leaves in hair', 'root-like feet'],
        buff: 'Plant Resilience', buff_description: '+25% damage resistance, heal 5 defiance at the start of each fight',
        effects: { 'damage_reduction' => 0.75, 'combat_start_regen' => 5 },
        special_event: 'Root Network',
        special_event_description: "Sometimes the tower's roots warn you about a foe, lowering its AGI for the fight",
        special: { kind: :insight, chance: 0.3,
                   text: "The tower's roots whisper the %<name>s's every move to you — its AGI drops by **%<amount>s** this fight." }
      },
      'alraune' => {
        name: 'Alraune', group: 'Plant',
        description: "You've become a predatory plant creature focused on luring prey",
        requirement: { plant_submissions: 10, futanari_events: 3, mind_control_events: 3 },
        appearance: ['petal-like skin', 'sweet scent', 'vine hair'],
        buff: 'Luring Scent', buff_description: '+25% seduction chance, +15% trap avoidance',
        effects: { 'satisfy_bonus' => 0.25, 'trap_avoid_bonus' => 0.15 },
        special_event: 'Digestive Trap',
        special_event_description: 'Sometimes your vines snare the monster, weakening it for the rest of the fight',
        special: { kind: :weaken, chance: 0.15,
                   text: 'Sticky vines snare the %<name>s and sap its strength — its attacks weaken!' }
      },
      'living_doll' => {
        name: 'Living Doll', group: 'Object',
        description: "You've become more object than person, with porcelain skin and jointed limbs",
        requirement: { objectification_events: 5, petplay_events: 3, mind_control_events: 3 },
        appearance: ['porcelain skin', 'jointed limbs', 'glass eyes'],
        buff: "Doll's Stillness", buff_description: '+20% damage resistance, can feign death',
        effects: { 'damage_reduction' => 0.8 },
        special_event: 'Toy Box',
        special_event_description: 'Sometimes you go perfectly still as a toy, and the monster loses interest for a turn',
        special: { kind: :stun, chance: 0.12,
                   text: 'You freeze into a lifeless doll — the %<name>s pokes you, confused, then startles when you move again!' }
      },
      'furniture' => {
        name: 'Furniture', group: 'Object',
        description: "You've lost your humanity, becoming literally functional furniture",
        requirement: { objectification_events: 10, slavery_events: 5, bondage_events: 3 },
        appearance: ['wood-like skin', 'functional shape'],
        events: { 'objectification' => 40, 'slavery' => 30, 'bondage' => 25 },
        buff: 'Functional Form', buff_description: '+30% damage resistance, can feign death perfectly',
        effects: { 'damage_reduction' => 0.7 },
        special_event: 'Furniture Surprise',
        special_event_description: 'Sometimes you trap the monster inside your furniture form, stopping its attack',
        special: { kind: :stun, chance: 0.12,
                   text: 'The %<name>s sits on you without thinking — and you clamp shut around it, trapping it for a turn!' }
      },
      'vampire' => {
        name: 'Vampire', group: 'Supernatural',
        description: "You've become a creature of the night — a thrall-maker with undead hunger",
        requirement: { undead_submissions: 15, mind_control_events: 3, slavery_events: 3 },
        appearance: ['pale skin', 'fangs', 'red eyes'],
        buff: 'Vampiric Charm', buff_description: '+25% seduction chance, heal 25% of the damage you deal',
        effects: { 'satisfy_bonus' => 0.25, 'lifesteal' => 0.25 },
        special_event: 'Thrall Making',
        special_event_description: 'Sometimes you briefly enthrall the monster and it attacks itself',
        special: { kind: :thrall, chance: 0.12,
                   text: 'Your red eyes catch the %<name>s — enthralled, it turns on itself for **%<amount>s** damage!' }
      },
      'ghost' => {
        name: 'Ghost', group: 'Supernatural',
        description: "You've become ethereal, partially intangible",
        requirement: { undead_submissions: 10, sensory_deprivation_events: 3, bondage_events: 3 },
        appearance: ['translucent body', 'floats', 'cold touch'],
        buff: 'Ethereal Form', buff_description: '+20% dodge chance, can pass through solid objects briefly',
        effects: { 'dodge_bonus' => 0.2 },
        special_event: 'Haunting',
        special_event_description: 'Sometimes you phase through the monster, draining it as you pass',
        special: { kind: :drain, chance: 0.15,
                   text: 'You phase straight through the %<name>s, draining **%<amount>s** HP and drinking it in as defiance!' }
      },
      'latexdoll' => {
        name: 'Latexdoll', group: 'Synthetic',
        description: 'Your skin has become shiny and synthetic, erasing your human features',
        requirement: { latex_events: 10, mind_control_events: 3 },
        appearance: ['rubber skin', 'featureless face', 'seamless body'],
        buff: 'Synthetic Skin', buff_description: '+25% damage resistance, immune to corrosion (half lust from slimes)',
        effects: { 'damage_reduction' => 0.75, 'slime_lust_mult' => 0.5 },
        special_event: 'Living Latex',
        special_event_description: 'Sometimes your skin wraps around the monster, restraining it for a turn',
        special: { kind: :stun, chance: 0.12,
                   text: 'Your glossy skin flows over the %<name>s and squeezes tight — it is restrained and loses its turn!' }
      },
      'rubberslime' => {
        name: 'Rubberslime', group: 'Synthetic',
        description: "You've become a hybrid of slime and rubber properties",
        requirement: { latex_events: 7, inflation_events: 3, slime_submissions: 7 },
        appearance: ['shiny translucent skin', 'amorphous shape'],
        buff: 'Elastic Form', buff_description: '+20% damage resistance, can stretch limbs',
        effects: { 'damage_reduction' => 0.8 },
        special_event: 'Encase',
        special_event_description: 'Sometimes you encase the monster in your rubbery body, crushing it',
        special: { kind: :crush, chance: 0.12,
                   text: 'You stretch over the %<name>s and encase it in rubber, squeezing for **%<amount>s** damage!' }
      },
      'angel' => {
        name: 'Angel', group: 'Holy',
        description: 'Your untouched purity has lifted you above the ruins — monsters shy from your light',
        requirement: { pure_title: true },
        appearance: ['feathered wings', 'soft halo', 'radiant skin'],
        monster_rate: 0.7,
        event_rate: 1.35,
        buff: 'Divine Presence', buff_description: '+20% damage resistance, +15% chance to intimidate monsters',
        effects: { 'damage_reduction' => 0.8, 'intimidate_chance' => 0.15 },
        special_event: 'Divine Intervention',
        special_event_description: 'When your defiance runs low, your light sometimes flares, driving the monster back and restoring you',
        special: { kind: :divine, chance: 0.35,
                   text: 'Your halo erupts in blinding light! The %<name>s recoils, and you recover **%<amount>s** defiance as your lust cools.' }
      }
    }.freeze

    MONSTER_LABELS = {
      beast: 'Beast', demon: 'Demon', slime: 'Slime', undead: 'Undead', plant: 'Plant', mimic: 'Mimic'
    }.freeze

    SKIP_KINDS = %i[stun thrall drain crush divine].freeze

    module_function

    def get(key)
      TRANSFORMATIONS[key.to_s]
    end

    def find(query)
      q = query.to_s.strip.downcase
      return nil if q.empty?

      TRANSFORMATIONS.find { |k, t| k == q || t[:name].downcase == q || k.tr('_', ' ') == q }&.first
    end

    def eligible?(player, key)
      entry = get(key)
      entry ? Engine::TitleSystem.met?(player, entry[:requirement]) : false
    end

    def visible(player)
      owned = player.unlocked_transformations
      TRANSFORMATIONS.select { |k, t| owned.include?(k) || Engine::TitleSystem.visible?(player, t) }
    end

    def active(player)
      get(player.active_transformation_key)
    end

    def effects(player)
      Hash(active(player)&.dig(:effects))
    end

    def monster_rate(player)
      active(player)&.dig(:monster_rate) || 1.0
    end

    def event_rate(player)
      active(player)&.dig(:event_rate) || 1.0
    end

    def monster_weight(player, type)
      form = active(player)
      return 1.0 unless form

      1.0 + (Hash(form[:monsters])[type.to_sym].to_i / 100.0)
    end

    def event_weight(player, tag)
      form = active(player)
      return 1.0 unless form

      bonus = form[:all_events].to_i
      bonus += Hash(form[:events])[tag.to_s].to_i if tag
      1.0 + (bonus / 100.0)
    end

    def combat_start!(player, enc, lines)
      special = active(player)&.dig(:special)
      return unless special && special[:kind] == :insight && rand < special[:chance]

      drop = [enc[:agility].to_i, 3].min
      return unless drop.positive?

      enc[:agility] = enc[:agility].to_i - drop
      lines << format("_#{special[:text]}_", name: enc[:name], amount: drop)
    end

    def combat_special!(player, enc, log)
      special = active(player)&.dig(:special)
      return nil unless special
      return nil if special[:kind] == :insight
      return nil if special[:kind] == :divine && player.defiance > (player.max_defiance * 0.3)
      return nil unless rand < special[:chance]

      amount = resolve_special!(player, enc, special[:kind])
      log << format("**#{active(player)[:special_event]}** — #{special[:text]}", name: enc[:name], amount: amount)
      SKIP_KINDS.include?(special[:kind]) ? :skip : :continue
    end

    def resolve_special!(player, enc, kind)
      floor = player.current_floor.to_i
      case kind
      when :absorb then player.heal_defiance!(5 + (floor / 2))
      when :dream
        lp = 3 + (floor / 3)
        player.gain_lp!(lp)
        lp
      when :weaken
        enc[:strength] = [(enc[:strength].to_i * 0.8).round, 1].max
        enc[:lust_damage] = [(enc[:lust_damage].to_i * 0.8).round, 1].max
        nil
      when :thrall then hurt!(enc, [enc[:strength].to_i, 1].max)
      when :crush then hurt!(enc, [(player.effective_strength * 1.5).round, 1].max)
      when :drain
        dealt = hurt!(enc, [(player.effective_strength / 2.0).round + (floor / 2), 1].max)
        player.heal_defiance!(dealt)
        dealt
      when :divine
        healed = player.heal_defiance!(15)
        player.update(lust: [player.lust - 15, player.base_lust].max)
        healed
      end
    end

    def hurt!(enc, damage)
      dealt = [damage, enc[:hp].to_i].min
      enc[:hp] = enc[:hp].to_i - dealt
      dealt
    end

    def effect_lines(entry)
      lines = []
      if entry[:monster_rate] && entry[:monster_rate] != 1.0
        lines << "Monster rooms #{signed_pct(entry[:monster_rate])}"
      end
      lines << "Random events #{signed_pct(entry[:event_rate])}" if entry[:event_rate] && entry[:event_rate] != 1.0
      lines << "Every event type +#{entry[:all_events]}%" if entry[:all_events].to_i.positive?
      Hash(entry[:monsters]).each { |type, pct| lines << "#{MONSTER_LABELS.fetch(type, type.to_s.capitalize)} monsters +#{pct}%" }
      Hash(entry[:events]).each do |tag, pct|
        label = Engine::ContentOptions.preference(tag)&.dig(:label) || tag.tr('_', ' ').capitalize
        lines << "#{label} events +#{pct}%"
      end
      lines << "**#{entry[:buff]}:** #{entry[:buff_description]}" if entry[:buff]
      lines << "**#{entry[:special_event]}:** #{entry[:special_event_description]}" if entry[:special_event]
      lines
    end

    def signed_pct(mult)
      pct = ((mult.to_f - 1) * 100).round
      pct.negative? ? "#{pct}%" : "+#{pct}%"
    end
  end
end
