# frozen_string_literal: true

# Copies the bot's game engine into webapp/ruby/bot/ so the browser game runs
# the same rules, events and text as Discord. Re-run after changing the bot:
#
#   ruby webapp/tools/sync_from_bot.rb
#
# The copies are generated: edit the bot sources, not webapp/ruby/bot/.
# Database-backed behaviour is replaced at runtime by webapp/ruby/web/*.rb.

require 'fileutils'
require 'json'

ROOT = File.expand_path('../..', __dir__)
WEB_RUBY = File.join(ROOT, 'webapp', 'ruby')
OUT = File.join(WEB_RUBY, 'bot')

# Load order matters: constants reference each other at load time.
BOT_FILES = %w[
  lib/character_archetypes.rb
  lib/models/player.rb
  lib/engine/tower.rb
  lib/engine/content_options.rb
  lib/engine/chastity_system.rb
  lib/engine/corruption.rb
  lib/engine/marks.rb
  lib/engine/elites.rb
  lib/engine/title_system.rb
  lib/engine/transformation_system.rb
  lib/engine/threat_calculator.rb
  lib/engine/monster_types.rb
  lib/engine/monster_scenes.rb
  lib/engine/curse_catalog.rb
  lib/engine/boss_fights.rb
  lib/engine/shop.rb
  lib/engine/treasure.rb
  lib/engine/event_packs/core.rb
  lib/engine/event_packs/body.rb
  lib/engine/event_packs/kink.rb
  lib/engine/event_packs/fetish.rb
  lib/engine/fetish_events.rb
  lib/engine/extra_events.rb
  lib/engine/random_events.rb
  lib/engine/npc_system.rb
  lib/engine/combat_engine.rb
  lib/engine/exploration.rb
].freeze

WEB_BEFORE = %w[web/shim.rb].freeze
WEB_AFTER = %w[web/records.rb web/player.rb web/engine.rb game.rb bridge.rb].freeze

# [file, exact text, replacement]. Each must match or the sync aborts.
PATCHES = [
  ['lib/engine/shop.rb',
   'DB[:player_curses].where(player_id: player.discord_id, curse_id: curse_to_remove.id).delete',
   'player.drop_curse!(curse_to_remove.name)']
].freeze

HEADER = "# Generated by webapp/tools/sync_from_bot.rb from %s. Do not edit; change the bot and re-sync.\n"

FileUtils.rm_rf(OUT)
BOT_FILES.each do |rel|
  src = File.read(File.join(ROOT, rel), encoding: 'UTF-8')
  src = src.lines.reject { |l| l.include?('require_relative') }.join

  PATCHES.select { |file, _, _| file == rel }.each do |_, from, to|
    abort "sync: patch target not found in #{rel}:\n  #{from}" unless src.include?(from)
    src = src.sub(from) { to }
  end

  dest = File.join(OUT, rel.sub(%r{\Alib/}, ''))
  FileUtils.mkdir_p(File.dirname(dest))
  File.write(dest, format(HEADER, rel) + src, mode: 'wb', encoding: 'UTF-8')
end

manifest = WEB_BEFORE + BOT_FILES.map { |rel| "bot/#{rel.sub(%r{\Alib/}, '')}" } + WEB_AFTER
File.write(File.join(WEB_RUBY, 'manifest.json'), "#{JSON.pretty_generate(manifest)}\n", mode: 'wb')

puts "Synced #{BOT_FILES.size} bot files into #{OUT}"
